INSERT INTO Ho_khau (Ma_ho_khau, Dia_diem, So_nha, Ten_duong, Ten_phuong, Ten_quan, Ten_thanh_pho, Da_xac_nhan, So_luong_xe_may, So_luong_o_to, Dien_tich) VALUES
(1, 'Chung cư BlueMoon', 'T1001', 'Văn Khê', 'Phú La', 'Hà Đông', 'Hà Nội', TRUE, 2, 1, 50),
(2, 'Chung cư BlueMoon','T1002', 'Văn Khê', 'Phú La', 'Hà Đông', 'Hà Nội', TRUE, 1, 1, 50),
(3, 'Chung cư BlueMoon','T1003', 'Văn Khê', 'Phú La', 'Hà Đông', 'Hà Nội', TRUE, 3, 0, 50),
(4, 'Chung cư BlueMoon','T1004', 'Văn Khê', 'Phú La', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 50),
(5, 'Chung cư BlueMoon','T1005', 'Văn Khê', 'Phú La', 'Hà Đông', 'Hà Nội', TRUE, 0, 1, 50),
(6, 'Chung cư BlueMoon','T1006', 'Văn Khê', 'Phú La', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 50),
(7, 'Chung cư BlueMoon','T1007', 'Văn Khê', 'Phú La', 'Hà Đông', 'Hà Nội', TRUE, 1, 1, 50),
(8, 'Chung cư BlueMoon','T1008', 'Văn Khê', 'Phú La', 'Hà Đông', 'Hà Nội', TRUE, 1, 0, 50),
(9, 'Chung cư BlueMoon','T1009', 'Văn Khê', 'Phú La', 'Hà Đông', 'Hà Nội', TRUE, 2, 1, 50),
(10, 'Chung cư BlueMoon','T1010', 'Văn Khê', 'Phú La', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 50),
(11, 'Tổ dân phố 7','151', 'Mậu Lương', 'La Khê', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 50),
(12, 'Tổ dân phố 7','152', 'Mậu Lương', 'La Khê', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 60),
(13, 'Tổ dân phố 7','153', 'Mậu Lương', 'La Khê', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 80),
(14, 'Tổ dân phố 7','154', 'Mậu Lương', 'La Khê', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 90),
(15, 'Tổ dân phố 7','155', 'Mậu Lương', 'La Khê', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 70),
(16, 'Tổ dân phố 7','156', 'Mậu Lương', 'La Khê', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 60),
(17, 'Tổ dân phố 7','157', 'Mậu Lương', 'La Khê', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 80),
(18, 'Tổ dân phố 7','158', 'Mậu Lương', 'La Khê', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 80),
(19, 'Tổ dân phố 7','159', 'Mậu Lương', 'La Khê', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 50),
(20, 'Tổ dân phố 7','160', 'Mậu Lương', 'La Khê', 'Hà Đông', 'Hà Nội', TRUE, 2, 0, 50);

